#!/usr/bin/env bash

# print the index of the currently focused niri workspace

digit=$(niri msg --json workspaces | jq -r 'map(select(.is_focused))[0].idx')

if [[ -n "$digit" && "$digit" != "null" ]]; then
  echo "$digit"
else
  exit 1
fi
