#!/usr/bin/env  bash
COVER="/tmp/eww_mp_thumbnail.png"
MUSIC_DIR="$HOME/Music"

# Just for too long labels
add_newlines() {
  string="$1"
  n="$2"
  count=0

  for ((i = 0; i < ${#string}; i++)); do
    echo -n "${string:i:1}"
    ((count++))

    if ((count == n)); then
      echo
      count=0
    fi
  done
}

get_cover() {
	ffmpeg -i "$MUSIC_DIR/$(mpc current -f %file%)" -map 0:v:0 -c copy "${COVER}" -y &> /dev/null
	STATUS=$?

	# Check if the file has a embbeded album art
	if [ "$STATUS" -eq 0 ];then
		echo "$COVER"
	else
		echo "images/icons/music.jpg"
	fi
}

get_artist() {
	ARTIST=$(mpc current -f %artist%)
	add_newlines "$ARTIST" 40
}

get_title() {
	TITLE=$(mpc current -f %title%)
	add_newlines "$TITLE" 40
}

get_time() {
  mpc status '%currenttime% - %totaltime%'
}

get_time_percentile() {
  # string="10%"; echo "${string/\%/}"
  TIME=$(mpc status '%percenttime%')
  echo "${TIME/\%/}"  | tr -d '[:space:]'
}

is_mpc_playing() {
    if mpc status | grep -q "\[playing\]"; then
        return 1
    else
        return 0
    fi
}

listen_meta() {
  CURRENT_TITLE=""

  while true; do
      TITLE=$(get_title)

      if [ "$CURRENT_TITLE" != "$TITLE" ] ; then
        CURRENT_TITLE=$TITLE
        ARTIST=$(get_artist)
        COVER=$(get_cover)

        LISTEN_META="{"
        LISTEN_META+="\"title\": \"$TITLE\", "
        LISTEN_META+="\"artist\": \"$ARTIST\", "
        LISTEN_META+="\"cover\": \"$COVER\""
        LISTEN_META+="}"

        echo "$LISTEN_META"
      fi

      sleep 2
  done
}

listen_playing_meta() {
  while true; do
    IS_PLAYING=$(is_mpc_playing && echo "true" || echo "false")
    TIME=$(get_time)
    PERCENTILE=$(get_time_percentile)

    LISTEN_PLAYING_META="{"
    LISTEN_PLAYING_META+="\"time\": \"$TIME\", "
    LISTEN_PLAYING_META+="\"playing\": \"$IS_PLAYING\", "
    LISTEN_PLAYING_META+="\"percentile\": \"$PERCENTILE\""
    LISTEN_PLAYING_META+="}"


    echo "$LISTEN_PLAYING_META"
    sleep 0.5
  done
}


while [[ "$#" -gt 0 ]]; do
    case $1 in
      --cover) get_cover;;
      --artist) get_artist;;
      --title) get_title;;
      --time) get_time;;
      --time_percent) get_time_percentile;;
      --listen_meta) listen_meta;;
      --listen_playing_meta) listen_playing_meta;;
      --is_playing) is_mpc_playing && echo "true" || echo "false";;
      *) return 1;;
    esac
    shift
done