#!/usr/bin/env lua

-- MIT License

-- Copyright (c) 2023 YorQat

-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:

-- The above copyright notice and this permission notice shall be included in all
-- copies or substantial portions of the Software.

-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-- SOFTWARE.

-- Contact: YorQat <qarkdev+gh@gmail.com>

-- Gets appropriate theme based on time of day
local currentHour = tonumber(os.date("%H"))
local result = ""

if currentHour >= 18 or currentHour < 6 then
    result = "dark"
else
    result = "light"
end

if #arg == 0 then
    io.write("themes/" .. result)

else
    for i = 1, #arg do
        if arg[i] == "--absolute-path" then
            -- Function to get the current working directory
            io.write(os.getenv("HOME") .. "/.config/eww/themes" .. "/" .. result)
        else
            -- Handle other arguments
        end
    end
end