#!/usr/bin/env bash

ACTIVE_WORKSPACE=$(~/.config/eww/scripts/active_workspace)
LIMIT=6

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --up)
            if [[ $(($ACTIVE_WORKSPACE + 1)) -gt $LIMIT ]]; then
                niri msg action focus-workspace "$LIMIT"
            else
                niri msg action focus-workspace $(($ACTIVE_WORKSPACE + 1))
            fi
            ;;
        --down) niri msg action focus-workspace $(($ACTIVE_WORKSPACE - 1));;
        *) niri msg action focus-workspace $(($ACTIVE_WORKSPACE + 1));;
    esac
    shift
done
