#!//usr/bin/env bash

# MIT License

# Copyright (c) 2023 YorQat

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Contact: YorQat <qarkdev+gh@gmail.com>

pkill swaybg
rm -f eww.scss
rm -f HOME_WALL

THEME=$(cat THEME)

if [[ $THEME == "dark" ]]
then 
  ln -s themes/light.scss eww.scss
  ln -s images/wallpapers/home.jpg HOME_WALL
  echo "light" > THEME
elif [[ $THEME == "light" ]]
then
  ln -s themes/dark.scss eww.scss
  ln -s images/wallpapers/retro-street.jpg HOME_WALL
  echo "dark" > THEME
fi

./scripts/startup-wallpaper 

eww reload
