#!//usr/bin/env bash

# MIT License

# Copyright (c) 2023 YorQat

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Contact: YorQat <qarkdev+gh@gmail.com>

# Get current theme from the existing eww instance
export THEME=$(eww -c . get theme)

OLD_BG_PROCESS=$(pgrep swaybg)

# For startup
if [ -z "$THEME" ]; then
  export THEME=$(./scripts/start_theme)
fi

#  swap them light and darks
if [[ $THEME == "themes/dark" ]]; then
  NEW_THEME="light"
elif [[ $THEME == "themes/light" ]]; then
  NEW_THEME="dark"
fi  

# launch bar and store the new state
# add in the wallpaper to spicet things up
pkill eww
eww -c ../$NEW_THEME open-many bar mp-mini notify-mini
eww -c ../$NEW_THEME update theme="themes/$NEW_THEME"
swaybg -i ../$NEW_THEME/HOME_WALL -m fill &

# window styling
./scripts/hypr_theme ../$NEW_THEME/hyprland.conf

kill $OLD_BG_PROCESS